=== veerpartapsingh001/Certification-Course-Lesson-1/Lab_Files/L13 Lab Files/example_XML/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT zoo ((mammals, reptiles, birds))> 
<!ELEMENT mammals ((species))>
<!ELEMENT species (#PCDATA)>
<!ELEMENT reptiles ((species))>
<!ELEMENT birds ((species))>

=== veerpartapsingh001/Certification-Course-Lesson-1/Lab_Files/L13 Lab Files/Lab13-1/example_XML.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE zoo SYSTEM "test.dtd">
<zoo>
  <mammals>
    <species> Lion </species>
    <species> Zebra </species>
    <species> Gorilla </species>
  </mammals>
  <reptiles>
    <species> Alligator </species>
    <species> Snake </species>
    <species> Turtle </species>
  </reptiles>
  <birds>
    <species> Eagle </species>
    <species> Duck </species>
  </birds>
</zoo>

=== veerpartapsingh001/Certification-Course-Lesson-1/Lab_Files/L13 Lab Files/example_XML/example_XML.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE zoo SYSTEM " https://s3.amazonaws.com/jigyaasa_download/1D0-735/Example_Files/example_XML/test.dtd">
<zoo>
  <mammals>
    <species> Lion </species>
    <species> Zebra </species>
    <species> Gorilla </species>
  </mammals>
  <reptiles>
    <species> Alligator </species>
    <species> Snake </species>
    <species> Turtle </species>
  </reptiles>
  <birds>
    <species> Eagle </species>
    <species> Duck </species>
  </birds>
</zoo>
